In [29]:
# импортируем регулярные выражения
import re

In [30]:
with open('train_data.txt', 'r', encoding='utf-8') as f:
    text = f.read()
    text = text.replace('\ufeff', '') # убираем первый невидимый символ
    text = re.sub(r'[^А-я ]', '', text) # убираем все недопустимые символы

In [31]:
text

'Вы  лучший ответ на проблемы которые возникли в понедельникДумайте позитивно и верьте в свою способность достигать отличных результатовЕсли вы смогли в понедельник подняться с постели значит вы супер герой'

In [32]:
len(text)

205

In [33]:
num_characters = 34 #33 буквы + пробел

In [34]:
import keras
from keras.preprocessing.text import Tokenizer

Сформируем словарь из символов нашего текста

In [35]:
tokenizer = Tokenizer(num_words=num_characters, char_level=True)

In [36]:
tokenizer.fit_on_texts(text)

In [37]:
print(tokenizer.word_index)

{' ': 1, 'о': 2, 'т': 3, 'е': 4, 'и': 5, 'в': 6, 'н': 7, 'с': 8, 'л': 9, 'п': 10, 'ь': 11, 'ы': 12, 'р': 13, 'а': 14, 'д': 15, 'у': 16, 'к': 17, 'з': 18, 'ч': 19, 'й': 20, 'м': 21, 'г': 22, 'б': 23, 'я': 24, 'ш': 25, 'ю': 26, 'х': 27}


In [38]:
inp_chars = 6 #
data = tokenizer.texts_to_matrix(text)

In [39]:
data[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [40]:
n = data.shape[0]-inp_chars
n  #размер обучающего множества (205 - inp_chars)

199

In [41]:
import numpy as np

In [42]:
X = np.array([data[i:i+inp_chars, :] for i in range(n)])
Y = data[inp_chars:] #предсказание следующего символа

In [43]:
len(X)

199

In [44]:
X[0]

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]])

In [45]:
Y[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [46]:
from keras.layers import *
from keras.models import Sequential

In [47]:
model = Sequential()
model.add(Input((inp_chars, num_characters)))
model.add(SimpleRNN(500, activation='tanh'))
model.add(Dense(num_characters, activation='softmax'))
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_2 (SimpleRNN)    (None, 500)               267500    
                                                                 
 dense_2 (Dense)             (None, 34)                17034     
                                                                 
Total params: 284534 (1.09 MB)
Trainable params: 284534 (1.09 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [48]:
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')
history = model.fit(X, Y, batch_size=32, epochs=100)

Epoch 1/100
7/7 [==============================] - 1s 19ms/step - loss: 3.3635 - accuracy: 0.0754
Epoch 2/100
7/7 [==============================] - 0s 20ms/step - loss: 2.4225 - accuracy: 0.3467
Epoch 3/100
7/7 [==============================] - 0s 19ms/step - loss: 1.8781 - accuracy: 0.4724
Epoch 4/100
7/7 [==============================] - 0s 19ms/step - loss: 1.5243 - accuracy: 0.5578
Epoch 5/100
7/7 [==============================] - 0s 20ms/step - loss: 1.2296 - accuracy: 0.6482
Epoch 6/100
7/7 [==============================] - 0s 19ms/step - loss: 1.0082 - accuracy: 0.7136
Epoch 7/100
7/7 [==============================] - 0s 21ms/step - loss: 0.8164 - accuracy: 0.7789
Epoch 8/100
7/7 [==============================] - 0s 20ms/step - loss: 0.7445 - accuracy: 0.8291
Epoch 9/100
7/7 [==============================] - 0s 32ms/step - loss: 0.6124 - accuracy: 0.8643
Epoch 10/100
7/7 [==============================] - 0s 27ms/step - loss: 0.5407 - accuracy: 0.8744
Epoch 11/100
7/7 [=

In [49]:
def buildPhrase(inp_str, str_len = 50):
  for i in range(str_len):
    x = []
    for j in range(i, i+inp_chars):
      x.append(tokenizer.texts_to_matrix(inp_str[j])) # преобразуем символы в One-Hot-encoding

    x = np.array(x)
    inp = x.reshape(1, inp_chars, num_characters)

    pred = model.predict( inp ) # предсказываем OHE четвертого символа
    d = tokenizer.index_word[pred.argmax(axis=1)[0]] # получаем ответ в символьном представлении

    inp_str += d # дописываем строку

  return inp_str

In [50]:
res = buildPhrase("утренн")
print(res)

1/1 [==============================] - 0s 75ms/step
утренновтовн  и верьте в свою способность достигать отли


# Слова


In [97]:
with open('train_data.txt', 'r', encoding='utf-8') as f:
    texts = f.read()
    texts = texts.replace('\ufeff', '') # убираем первый невидимый символ

In [104]:
texts

'Вы — лучший ответ на проблемы, которые возникли в понедельник.\nДумайте позитивно и верьте в свою способность достигать отличных результатов.\nЕсли вы смогли в понедельник подняться с постели, значит вы супер герой.'

In [105]:
maxWordsCount = 1000
tokenizer = Tokenizer(num_words=maxWordsCount, filters='!–"—#$%&amp;()*+,-./:;<=>?@[\\]^_`{|}~\t\n\r«»',
                       lower=True, split=' ', char_level=False)

In [106]:
tokenizer.fit_on_texts([texts])

In [107]:
dist = list(tokenizer.word_counts.items())
print(dist[:10])

[('вы', 3), ('лучший', 1), ('ответ', 1), ('на', 1), ('проблемы', 1), ('которые', 1), ('возникли', 1), ('в', 3), ('понедельник', 2), ('думайте', 1)]


In [124]:
data = tokenizer.texts_to_sequences([texts])

In [ ]:
data[0]

In [118]:
len(data[0])

31

In [111]:
res = keras.utils.to_categorical(data[0], num_classes=maxWordsCount)
print( res.shape )

(31, 1000)


In [ ]:
res[0]

In [113]:
inp_words = 3
n = res.shape[0]-inp_words
n

28

In [121]:
X = np.array([res[i:i+inp_words, :] for i in range(n)])
Y = res[inp_words:]

In [122]:
model = Sequential()
model.add(Input((inp_words, maxWordsCount)))
model.add(SimpleRNN(128, activation='tanh'))
model.add(Dense(maxWordsCount, activation='softmax'))
model.summary()

model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_4 (SimpleRNN)    (None, 128)               144512    
                                                                 
 dense_4 (Dense)             (None, 1000)              129000    
                                                                 
Total params: 273512 (1.04 MB)
Trainable params: 273512 (1.04 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [123]:
history = model.fit(X, Y, batch_size=32, epochs=19)

Epoch 1/19
1/1 [==============================] - 1s 1s/step - loss: 6.9199 - accuracy: 0.0000e+00
Epoch 2/19
1/1 [==============================] - 0s 22ms/step - loss: 6.8939 - accuracy: 0.0000e+00
Epoch 3/19
1/1 [==============================] - 0s 20ms/step - loss: 6.8678 - accuracy: 0.0357
Epoch 4/19
1/1 [==============================] - 0s 23ms/step - loss: 6.8414 - accuracy: 0.1786
Epoch 5/19
1/1 [==============================] - 0s 29ms/step - loss: 6.8144 - accuracy: 0.3214
Epoch 6/19
1/1 [==============================] - 0s 17ms/step - loss: 6.7867 - accuracy: 0.5357
Epoch 7/19
1/1 [==============================] - 0s 17ms/step - loss: 6.7578 - accuracy: 0.6786
Epoch 8/19
1/1 [==============================] - 0s 17ms/step - loss: 6.7275 - accuracy: 0.7857
Epoch 9/19
1/1 [==============================] - 0s 17ms/step - loss: 6.6954 - accuracy: 0.9286
Epoch 10/19
1/1 [==============================] - 0s 17ms/step - loss: 6.6612 - accuracy: 0.9643
Epoch 11/19
1/1 [======

In [90]:
def buildPhrase(texts, str_len = 20):
  res = texts
  data = tokenizer.texts_to_sequences([texts])[0]
  for i in range(str_len):
    x = keras.utils.to_categorical(data[i: i+inp_words], num_classes=maxWordsCount) # преобразуем в One-Hot-encoding
    inp = x.reshape(1, inp_words, maxWordsCount)
    pred = model.predict( inp ) # предсказываем OHE четвертого символа
    indx = pred.argmax(axis=1)[0]
    data.append(indx)
    res += " " + tokenizer.index_word[indx] # дописываем строку
  return res

In [91]:
for i in range(1):
    x = keras.utils.to_categorical(data[i: i+inp_words], num_classes=maxWordsCount)

In [92]:
x.shape

(1, 31, 1000)

In [132]:
i = 0

In [133]:
x = keras.utils.to_categorical(data[i: i+inp_words], num_classes=maxWordsCount) # преобразуем в One-Hot-encoding
x

array([], shape=(3, 0, 1000), dtype=float32)

**Размерности не совпадают!**

In [134]:
inp = x.reshape(1, inp_words, maxWordsCount)
inp

ValueError: cannot reshape array of size 0 into shape (1,3,1000)

In [94]:
test_0 = "позитив добавляет годы"

In [125]:
data = tokenizer.texts_to_sequences(test_0)

In [96]:
data = tokenizer.texts_to_sequences([test_0])[0]
data

[]

In [131]:
data

[[],
 [],
 [],
 [12],
 [],
 [12],
 [2],
 [],
 [],
 [],
 [],
 [],
 [2],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 []]

In [93]:
res = buildPhrase("позитив добавляет годы")
print(res)

ValueError: cannot reshape array of size 0 into shape (1,3,1000)